server:
  port: 8882
#spring:
  #zipkin:
    #base:
      #url: http://localhost:9411
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
    virtual-host: /
  #sleuth:
    #sampler:
      #percentage: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

