eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
   port: 8892
spring:
   application:
      name: service-feign
# 使用断路器 配置
feign:
  hystrix:
    enabled: true
  # 声明使用Apache HttpClient替换Feign原生httpclient
  httpclient:
    enabled: true
